services:
  node-a:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    command:
      - ./counter-server
      - -config
      - configs/node1.yaml
    environment:
      - COUNTER_LOG_LEVEL=debug
    ports:
      - "50051:50051"
      - "8080:8080" # Prometheus metrics
    networks:
      - counter-net

  node-b:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    command:
      - ./counter-server
      - -config
      - configs/node2.yaml
    environment:
      - COUNTER_LOG_LEVEL=debug
    ports:
      - "50052:50052"
      - "8081:8081"
    networks:
      - counter-net

  node-c:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    command:
      - ./counter-server
      - -config
      - configs/node3.yaml
    environment:
      - COUNTER_LOG_LEVEL=debug
    ports:
      - "50053:50053"
      - "8082:8082"
    networks:
      - counter-net

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - counter-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-rules.yml:/etc/prometheus/rules/prometheus-rules.yml
    ports:
      - "9090:9090"
    networks:
      - counter-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    networks:
      - counter-net

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - counter-net

networks:
  counter-net:
    driver: bridge

volumes:
  redis-data:
