// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: api/proto/counter.proto

package counter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateUpdate_UpdateType int32

const (
	StateUpdate_FULL_STATE   StateUpdate_UpdateType = 0
	StateUpdate_DELTA_UPDATE StateUpdate_UpdateType = 1
	StateUpdate_HEARTBEAT    StateUpdate_UpdateType = 2
)

// Enum value maps for StateUpdate_UpdateType.
var (
	StateUpdate_UpdateType_name = map[int32]string{
		0: "FULL_STATE",
		1: "DELTA_UPDATE",
		2: "HEARTBEAT",
	}
	StateUpdate_UpdateType_value = map[string]int32{
		"FULL_STATE":   0,
		"DELTA_UPDATE": 1,
		"HEARTBEAT":    2,
	}
)

func (x StateUpdate_UpdateType) Enum() *StateUpdate_UpdateType {
	p := new(StateUpdate_UpdateType)
	*p = x
	return p
}

func (x StateUpdate_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateUpdate_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_counter_proto_enumTypes[0].Descriptor()
}

func (StateUpdate_UpdateType) Type() protoreflect.EnumType {
	return &file_api_proto_counter_proto_enumTypes[0]
}

func (x StateUpdate_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateUpdate_UpdateType.Descriptor instead.
func (StateUpdate_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{6, 0}
}

// Request & Response Messages
type IncrementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         int32                  `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"` // how much to increment (default: 1)
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementRequest) Reset() {
	*x = IncrementRequest{}
	mi := &file_api_proto_counter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementRequest) ProtoMessage() {}

func (x *IncrementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementRequest.ProtoReflect.Descriptor instead.
func (*IncrementRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{0}
}

func (x *IncrementRequest) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *IncrementRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *IncrementRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DecrementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         int32                  `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrementRequest) Reset() {
	*x = DecrementRequest{}
	mi := &file_api_proto_counter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementRequest) ProtoMessage() {}

func (x *DecrementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementRequest.ProtoReflect.Descriptor instead.
func (*DecrementRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{1}
}

func (x *DecrementRequest) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *DecrementRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DecrementRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // optional: get value from specific node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	mi := &file_api_proto_counter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{2}
}

func (x *GetValueRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_api_proto_counter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{3}
}

type CounterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CurrentValue  int64                  `protobuf:"varint,2,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                             // Vector Clock representation
	LastUpdated   int64                  `protobuf:"varint,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"` // Unix timestamp
	ClusterNodes  []*NodeInfo            `protobuf:"bytes,5,rep,name=cluster_nodes,json=clusterNodes,proto3" json:"cluster_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterResponse) Reset() {
	*x = CounterResponse{}
	mi := &file_api_proto_counter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterResponse) ProtoMessage() {}

func (x *CounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterResponse.ProtoReflect.Descriptor instead.
func (*CounterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{4}
}

func (x *CounterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CounterResponse) GetCurrentValue() int64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *CounterResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CounterResponse) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *CounterResponse) GetClusterNodes() []*NodeInfo {
	if x != nil {
		return x.ClusterNodes
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	CounterValue  int64                  `protobuf:"varint,3,opt,name=counter_value,json=counterValue,proto3" json:"counter_value,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	IsLeader      bool                   `protobuf:"varint,5,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	LastSeen      int64                  `protobuf:"varint,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_api_proto_counter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{5}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetCounterValue() int64 {
	if x != nil {
		return x.CounterValue
	}
	return 0
}

func (x *NodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeInfo) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *NodeInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// Gossip Protocol Messages
type StateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    string                 `protobuf:"bytes,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	CounterValue  int64                  `protobuf:"varint,2,opt,name=counter_value,json=counterValue,proto3" json:"counter_value,omitempty"`
	PositiveDelta int64                  `protobuf:"varint,3,opt,name=positive_delta,json=positiveDelta,proto3" json:"positive_delta,omitempty"` // PNCounter specific
	NegativeDelta int64                  `protobuf:"varint,4,opt,name=negative_delta,json=negativeDelta,proto3" json:"negative_delta,omitempty"` // PNCounter specific
	VectorClock   string                 `protobuf:"bytes,5,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`        // JSON representation
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          StateUpdate_UpdateType `protobuf:"varint,7,opt,name=type,proto3,enum=counter.StateUpdate_UpdateType" json:"type,omitempty"`
	Metadata      map[string]int64       `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_api_proto_counter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{6}
}

func (x *StateUpdate) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *StateUpdate) GetCounterValue() int64 {
	if x != nil {
		return x.CounterValue
	}
	return 0
}

func (x *StateUpdate) GetPositiveDelta() int64 {
	if x != nil {
		return x.PositiveDelta
	}
	return 0
}

func (x *StateUpdate) GetNegativeDelta() int64 {
	if x != nil {
		return x.NegativeDelta
	}
	return 0
}

func (x *StateUpdate) GetVectorClock() string {
	if x != nil {
		return x.VectorClock
	}
	return ""
}

func (x *StateUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StateUpdate) GetType() StateUpdate_UpdateType {
	if x != nil {
		return x.Type
	}
	return StateUpdate_FULL_STATE
}

func (x *StateUpdate) GetMetadata() map[string]int64 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Membership Messages
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	StartupTime   int64                  `protobuf:"varint,3,opt,name=startup_time,json=startupTime,proto3" json:"startup_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_api_proto_counter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{7}
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *JoinRequest) GetStartupTime() int64 {
	if x != nil {
		return x.StartupTime
	}
	return 0
}

type MemberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	mi := &file_api_proto_counter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{8}
}

func (x *MemberList) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *MemberList) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	CounterValue  int64                  `protobuf:"varint,5,opt,name=counter_value,json=counterValue,proto3" json:"counter_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_api_proto_counter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{9}
}

func (x *Member) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Member) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Member) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Member) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *Member) GetCounterValue() int64 {
	if x != nil {
		return x.CounterValue
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CurrentValue  int64                  `protobuf:"varint,2,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_counter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentValue() int64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ClusterSize   int64                  `protobuf:"varint,3,opt,name=cluster_size,json=clusterSize,proto3" json:"cluster_size,omitempty"`
	ActiveMembers []*Member              `protobuf:"bytes,4,rep,name=active_members,json=activeMembers,proto3" json:"active_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_counter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_counter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_counter_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetClusterSize() int64 {
	if x != nil {
		return x.ClusterSize
	}
	return 0
}

func (x *HeartbeatResponse) GetActiveMembers() []*Member {
	if x != nil {
		return x.ActiveMembers
	}
	return nil
}

var File_api_proto_counter_proto protoreflect.FileDescriptor

const file_api_proto_counter_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/counter.proto\x12\acounter\"c\n" +
	"\x10IncrementRequest\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\x05R\x05delta\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"c\n" +
	"\x10DecrementRequest\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\x05R\x05delta\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"*\n" +
	"\x0fGetValueRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x14\n" +
	"\x12GetNodeInfoRequest\"\xc4\x01\n" +
	"\x0fCounterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rcurrent_value\x18\x02 \x01(\x03R\fcurrentValue\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12!\n" +
	"\flast_updated\x18\x04 \x01(\x03R\vlastUpdated\x126\n" +
	"\rcluster_nodes\x18\x05 \x03(\v2\x11.counter.NodeInfoR\fclusterNodes\"\xb6\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12#\n" +
	"\rcounter_value\x18\x03 \x01(\x03R\fcounterValue\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1b\n" +
	"\tis_leader\x18\x05 \x01(\bR\bisLeader\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\x03R\blastSeen\"\xd4\x03\n" +
	"\vStateUpdate\x12 \n" +
	"\ffrom_node_id\x18\x01 \x01(\tR\n" +
	"fromNodeId\x12#\n" +
	"\rcounter_value\x18\x02 \x01(\x03R\fcounterValue\x12%\n" +
	"\x0epositive_delta\x18\x03 \x01(\x03R\rpositiveDelta\x12%\n" +
	"\x0enegative_delta\x18\x04 \x01(\x03R\rnegativeDelta\x12!\n" +
	"\fvector_clock\x18\x05 \x01(\tR\vvectorClock\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x123\n" +
	"\x04type\x18\a \x01(\x0e2\x1f.counter.StateUpdate.UpdateTypeR\x04type\x12>\n" +
	"\bmetadata\x18\b \x03(\v2\".counter.StateUpdate.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"=\n" +
	"\n" +
	"UpdateType\x12\x0e\n" +
	"\n" +
	"FULL_STATE\x10\x00\x12\x10\n" +
	"\fDELTA_UPDATE\x10\x01\x12\r\n" +
	"\tHEARTBEAT\x10\x02\"c\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12!\n" +
	"\fstartup_time\x18\x03 \x01(\x03R\vstartupTime\"Q\n" +
	"\n" +
	"MemberList\x12)\n" +
	"\amembers\x18\x01 \x03(\v2\x0f.counter.MemberR\amembers\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\xa4\x01\n" +
	"\x06Member\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12%\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\x03R\rlastHeartbeat\x12#\n" +
	"\rcounter_value\x18\x05 \x01(\x03R\fcounterValue\"n\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rcurrent_value\x18\x02 \x01(\x03R\fcurrentValue\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xa2\x01\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fcluster_size\x18\x03 \x01(\x03R\vclusterSize\x126\n" +
	"\x0eactive_members\x18\x04 \x03(\v2\x0f.counter.MemberR\ractiveMembers2\xd0\x03\n" +
	"\x0eCounterService\x12@\n" +
	"\tIncrement\x12\x19.counter.IncrementRequest\x1a\x18.counter.CounterResponse\x12@\n" +
	"\tDecrement\x12\x19.counter.DecrementRequest\x1a\x18.counter.CounterResponse\x12>\n" +
	"\bGetValue\x12\x18.counter.GetValueRequest\x1a\x18.counter.CounterResponse\x12=\n" +
	"\vGetNodeInfo\x12\x1b.counter.GetNodeInfoRequest\x1a\x11.counter.NodeInfo\x12;\n" +
	"\tSyncState\x12\x14.counter.StateUpdate\x1a\x14.counter.StateUpdate(\x010\x01\x12:\n" +
	"\vJoinCluster\x12\x14.counter.JoinRequest\x1a\x13.counter.MemberList0\x01\x12B\n" +
	"\tHeartbeat\x12\x19.counter.HeartbeatRequest\x1a\x1a.counter.HeartbeatResponseB;Z9github.com/VeryFach/distributed-counter/api/proto;counterb\x06proto3"

var (
	file_api_proto_counter_proto_rawDescOnce sync.Once
	file_api_proto_counter_proto_rawDescData []byte
)

func file_api_proto_counter_proto_rawDescGZIP() []byte {
	file_api_proto_counter_proto_rawDescOnce.Do(func() {
		file_api_proto_counter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_counter_proto_rawDesc), len(file_api_proto_counter_proto_rawDesc)))
	})
	return file_api_proto_counter_proto_rawDescData
}

var file_api_proto_counter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_counter_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_counter_proto_goTypes = []any{
	(StateUpdate_UpdateType)(0), // 0: counter.StateUpdate.UpdateType
	(*IncrementRequest)(nil),    // 1: counter.IncrementRequest
	(*DecrementRequest)(nil),    // 2: counter.DecrementRequest
	(*GetValueRequest)(nil),     // 3: counter.GetValueRequest
	(*GetNodeInfoRequest)(nil),  // 4: counter.GetNodeInfoRequest
	(*CounterResponse)(nil),     // 5: counter.CounterResponse
	(*NodeInfo)(nil),            // 6: counter.NodeInfo
	(*StateUpdate)(nil),         // 7: counter.StateUpdate
	(*JoinRequest)(nil),         // 8: counter.JoinRequest
	(*MemberList)(nil),          // 9: counter.MemberList
	(*Member)(nil),              // 10: counter.Member
	(*HeartbeatRequest)(nil),    // 11: counter.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 12: counter.HeartbeatResponse
	nil,                         // 13: counter.StateUpdate.MetadataEntry
}
var file_api_proto_counter_proto_depIdxs = []int32{
	6,  // 0: counter.CounterResponse.cluster_nodes:type_name -> counter.NodeInfo
	0,  // 1: counter.StateUpdate.type:type_name -> counter.StateUpdate.UpdateType
	13, // 2: counter.StateUpdate.metadata:type_name -> counter.StateUpdate.MetadataEntry
	10, // 3: counter.MemberList.members:type_name -> counter.Member
	10, // 4: counter.HeartbeatResponse.active_members:type_name -> counter.Member
	1,  // 5: counter.CounterService.Increment:input_type -> counter.IncrementRequest
	2,  // 6: counter.CounterService.Decrement:input_type -> counter.DecrementRequest
	3,  // 7: counter.CounterService.GetValue:input_type -> counter.GetValueRequest
	4,  // 8: counter.CounterService.GetNodeInfo:input_type -> counter.GetNodeInfoRequest
	7,  // 9: counter.CounterService.SyncState:input_type -> counter.StateUpdate
	8,  // 10: counter.CounterService.JoinCluster:input_type -> counter.JoinRequest
	11, // 11: counter.CounterService.Heartbeat:input_type -> counter.HeartbeatRequest
	5,  // 12: counter.CounterService.Increment:output_type -> counter.CounterResponse
	5,  // 13: counter.CounterService.Decrement:output_type -> counter.CounterResponse
	5,  // 14: counter.CounterService.GetValue:output_type -> counter.CounterResponse
	6,  // 15: counter.CounterService.GetNodeInfo:output_type -> counter.NodeInfo
	7,  // 16: counter.CounterService.SyncState:output_type -> counter.StateUpdate
	9,  // 17: counter.CounterService.JoinCluster:output_type -> counter.MemberList
	12, // 18: counter.CounterService.Heartbeat:output_type -> counter.HeartbeatResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_counter_proto_init() }
func file_api_proto_counter_proto_init() {
	if File_api_proto_counter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_counter_proto_rawDesc), len(file_api_proto_counter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_counter_proto_goTypes,
		DependencyIndexes: file_api_proto_counter_proto_depIdxs,
		EnumInfos:         file_api_proto_counter_proto_enumTypes,
		MessageInfos:      file_api_proto_counter_proto_msgTypes,
	}.Build()
	File_api_proto_counter_proto = out.File
	file_api_proto_counter_proto_goTypes = nil
	file_api_proto_counter_proto_depIdxs = nil
}
